SE2017/faculty/urls.py
from django.conf.urls import url

from . import views

app_name='faculty'
urlpatterns =[
	
         url(r'^ViewProfs/$',views.ViewProfs,name='ViewProfs'),
 url(r'^ViewAttendance/$',views.ViewAttendance,name='ViewAttendance'),   
url(r'^ViewRegisteredStudents/$',views.ViewRegisteredStudents,name='ViewRegisteredStudents'), 
url(r'^AddAssignment/$',views.AddAssignment,name='AddAssignment'),   
url(r'^Delass/$',views.Delass,name='Delass'),  
url(r'^delete/$',views.delete,name='delete'), 
url(r'^offercourses/$',views.OfferCourses,name='OfferCourses'), 
url(r'^editdescription/$',views.EditCourseDescription,name='EditCourseDescription'), 
url(r'^coursepage/$',views.CoursePage,name='CoursePage'),
url(r'^entermarks/$',views.EnterMarks,name='index'), 
        
        
	
    ]

SE2017/urls.py
###################################################
# SE2017/urls.py: Consists of all the valid urls of SAMS-IIITS
#__authors__ = "Sri Harsha Gajavalli", "SriRamKumar", "Savitha"
#__copyright__ = "Copyright 2017, SE2017 Course"
#__Team__ = ["Sri Harsha Gajavalli", "Savitha", "SriRamKumar"]
#__license__ = "MIT"
#__version__ = "1.2"
#__maintainer__ = "SriRamKumr"
#__email__ = "sriramkumar.t15@iiits.in"
#__status__ = "Development"
####################################################


"""SE2017 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets



urlpatterns = [
	url(r'^$', include('home.urls'), name='home'),
    url(r'^login/',  auth_views.login, {'template_name': 'Login/login.html'}, name='login'),
	url(r'^logout/$', auth_views.logout, {'template_name': 'Login/login.html'}, name='logout'),
	url(r'^student/', include('students.urls'), name='student'),
	url(r'^faculty/', include('faculty.urls'), name='faculty'),
    url(r'^admin/', admin.site.urls),
    url(r'^api/',include('home.urls')),

]

SE2017/faculty/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

SE2017/faculty/forms.py
from django import forms

class UploadFileForm(forms.Form):
    
    file = forms.FileField()

SE2017/faculty/views.py
from __future__ import unicode_literals
from django.template.context import RequestContext
from home.models import Workbooks
import json as simplejson
from django.http import HttpResponse
import json
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.template import loader
from django.shortcuts import render_to_response
from home.models import *
from home.models import Assignment
from .forms import UploadFileForm


def ViewProfs(request):
    CourseList = []
    if request.user.personnel.Role.Role_name == 'Faculty':
	request.session['Prof_Name']=request.user.username
        person_id = request.user.personnel.Person_ID
        IC = Instructors_Courses.objects.all()
        for i in range(0, len(IC)):
            if person_id == IC[i].Inst_ID.Person_ID:
                CourseList.append(IC[i].Course_ID.Course_Name)
	if CourseList==[]:
            flag=0
	    
	else:
            flag=1
    template = loader.get_template('prof.html')
    context = {'flag':flag,'Courses':CourseList,'Prof_Name':request.session['Prof_Name']}
    return HttpResponse(template.render(context, request))
def CoursePage(request):		
	if request.POST.get('action')=='Save':
		course=Courses.objects.get(Course_Name=request.session['course'])
		course.Course_description = request.POST.get('coursedes')
        	course.save()		
	elif request.POST.get('action')=="submit":
		request.session['course'] =request.POST.get('dropdown')
	course=Courses.objects.get(Course_Name=request.session['course']) 				
    	template = loader.get_template('prof1.html')
    	context = {'Course':course,'CourseName':request.session['course']}
    	return HttpResponse(template.render(context, request))
	
				
		
		
	

def ViewRegisteredStudents(request):
    studentlist = []
    course_name = request.GET.get('name')
    students = Students_Courses.objects.all()
    for student in students:
        if course_name == student.Course_ID.Course_Name:
            studentlist.append(student.Student_ID.LDAP.username)
    template = loader.get_template('student.html')
    context = {'Students': json.dumps(studentlist), 'Course': course_name}
    return HttpResponse(template.render(context, request))


def AddAssignment(request):

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            courses = Courses.objects.all()
            for corse in courses:
                if corse.Course_Name == request.session['course']:
                    course = Courses.objects.get(Course_Name=corse.Course_Name)
                    break
            instance = Assignment(Course_ID=course, Assignment_File=request.FILES['file'])
            instance.save()
	     
	    
    else:
        CourseList = []
        form = UploadFileForm()
        
    return render(request, 'forms.html',
                 {'CourseName':request.session['course'], 'form': form, 'request': request})


def delete(request):
    if request.method != 'POST':
        raise Http404
    docId = request.POST.getlist('Assignment_File[]')
    for did in docId:
        docToDel = get_object_or_404(Assignment, Assign_ID=did)
        docToDel.Assignment_File.delete()
        docToDel.delete()
    return HttpResponse("Your File has been deleted successfully!!! ")


def Delass(request):
     asslist = []
     Assignments = Assignment.objects.all()
     for ass in Assignments:
     	if ass.Course_ID.Course_Name ==request.session['course']:
        	asslist.append(ass)
     return render(request, 'assignment.html', {'Assignments': asslist,'CourseName':request.session['course']})
   


def EditCourseDescription(request):
    if request.method == 'POST':
        course = request.POST.get('dropdown')
        courseobj = Courses.objects.get(Course_Name=course)
        courseobj.Course_description = request.POST.get('coursedes')
        courseobj.save()

        return HttpResponse("Successfully updated!!!")
    


def OfferCourses(request):
    if request.method == 'POST':
        person_id = request.user.personnel.Person_ID
        person = Personnel.objects.get(Person_ID=person_id)
        courseids = request.POST.getlist('courses[]')
        startdate = request.POST.get('startdate')
        enddate = request.POST.get('enddate')
        for cid in courseids:
            corse = Courses.objects.get(Course_ID=cid)
            IC = Instructors_Courses(Course_ID=corse, Inst_ID=person, Start_Date=startdate, End_Date=enddate)
            IC.save()
    else:
        IC = Instructors_Courses.objects.all()
        IClist = []
        for ic in IC:
            IClist.append(ic.Course_ID)
        person_id = request.user.personnel.Person_ID
        courses = Courses.objects.all()
        courses1 = []
        for corse in courses:
            if corse not in IClist:
                courses1.append(corse)
        template = loader.get_template('reg.html')
        context = {'Courses': courses1,'CourseName':request.session['course'], 'IC': IClist, 'Prof_Name': request.user.username}
    return HttpResponse(template.render(context, request))
def ViewAttendance(request):	
    	studentcount={}
	sessioncount=0
	students=Attendance.objects.all()
    	classes=Attendance_Session.objects.all()
	for Class in classes:
		if Class.Course_Slot.Course_ID.Course_Name==request.session['course']:
			sessioncount=sessioncount+1
		
	for student in students:
		value=[0,1]
		value[0]=student.Student_ID.LDAP.username
		value[1]=0
		studentcount[student.Student_ID.Person_ID]=value	
	for student in students:
		if student.ASession_ID.Course_Slot.Course_ID.Course_Name==request.session['course'] and student.Marked=='A':
			studentcount[student.Student_ID.Person_ID][1]=studentcount[student.Student_ID.Person_ID][1]+1
	if request.method=="POST":
		return HttpResponse(request.POST.get('abc'))			    
    	template = loader.get_template('attendance.html')
    	context = {'classes':studentcount,'CourseName':request.session['course'],'workingdays':sessioncount}
    	return HttpResponse(template.render(context, request))	
def EnterMarks(request):
	assignidlist=[]
	idlist=[]
	studentlist=[]
	studentdict={}
	assignid=Assignment.objects.all()
	students=Students_Courses.objects.all()
	
	for assign in assignid:
		if assign.Course_ID.Course_Name==request.session['course']:
			assignidlist.append(assign.Assign_ID)
	for student in students:
		if student.Course_ID.Course_Name==request.session['course']:
			studentlist.append(student)
			studentdict[student.Student_ID.Person_ID]=[]
	for i in range(1,len(assignid)+1):
		idlist.append(i)
	if request.method=="POST":
		return HttpResponse(request.POST.get('assign'))
	template = loader.get_template('marks.html')
    	context = {'assignid':idlist,'CourseName':request.session['course'],'students':studentlist,'studentdict':studentdict}
    	return HttpResponse(template.render(context, request))
def index(request):
    template = 'sheet.html'
 
    app_action = request.POST.get('app_action')
    posted_data = request.POST.get('json_data')
 
    if posted_data is not None and app_action == 'save':
        this_sheet = request.POST.get("sheet")
        this_workbook = request.POST.get("workbook_name")
        sheet_id = request.POST.get("sheet_id")
 
        posted_data = json.dumps(posted_data)
 
        if(sheet_id):
            wb = Workbooks(id=sheet_id, workbook_name=this_workbook, 
                   sheet_name=this_sheet, data=posted_data)
        else:
            wb = Workbooks(workbook_name=this_workbook, 
                   sheet_name=this_sheet, data=posted_data)
        wb.save()
 
    elif app_action == 'get_sheets':
        wb_name = request.POST.get('workbook_name')
        sheets = Workbooks.objects.filter(workbook_name=wb_name)
 
        # use list comprehension to create python list which is like a JSON object
        sheets = [{ "sheet_id":i.id, "workbook_name": i.workbook_name.encode("utf-8"),
                    "sheet_name": i.sheet_name.encode("utf-8"), 
                    "data": json.loads(i.data.encode("utf-8"))} for i in sheets ]
 
        # dumps -> serialize to JSON
        sheets = json.dumps(sheets)
 
        return HttpResponse( sheets, mimetype='application/javascript' )
 
    elif app_action == 'list':
        workbooks = Workbooks.objects.values('workbook_name').distinct()
 
        # use list comprehension to make a list of just the work books names
        workbooks = [ i['workbook_name'] for i in workbooks ]
 
        # encode into json format before sending to page
        workbooks = json.dumps(workbooks)
 
        # We need to return an HttpResponse object in order to complete
        # the ajax call
        return HttpResponse( workbooks, mimetype='application/javascript' )
 
    return render(request, template,{})

SE2017/faculty/templates/assignment.html
{% extends "navbar.html" %}
{% block core %}
 <a class="navbar-brand" id="navcourse" href="{% url 'faculty:CoursePage' %}">{{CourseName}}</a>
{% endblock %}
{% block addcontent %}
<center>
<br>

{% if Assignments %}
<ul>
	<h1> Available Assignments </h1>
    {% for document in Assignments %}
    
            
	<a href="{{document.Assignment_File.url}}">{{ document.Assignment_File.name }}</a><br>
    {% endfor %}
<br>

        
</ul>
{% else %}

<h1 style="color:red;">OOPS! No documents</h1> 
{% endif %}
</center>
{% endblock %}

SE2017/faculty/templates/attendance.html
{% extends "navbar.html" %}
{% block core %}
 <a class="navbar-brand" id="navcourse" href="{% url 'faculty:CoursePage' %}">{{CourseName}}</a>
{% endblock %}
<script>
function addColumn(tblId)
{
	var tblHeadObj = document.getElementById(tblId).tHead;
	for (var h=0; h<tblHeadObj.rows.length; h++) {
		var newTH = document.createElement('th');
		tblHeadObj.rows[h].appendChild(newTH);
		newTH.innerHTML = '[th] row:' + h + ', cell: ' + (tblHeadObj.rows[h].cells.length - 1)
	}

	var tblBodyObj = document.getElementById(tblId).tBodies[0];
	for (var i=0; i<tblBodyObj.rows.length; i++) {
		var newCell = tblBodyObj.rows[i].insertCell(-1);
		newCell.innerHTML = '[td] row:' + i + ', cell: ' + (tblBodyObj.rows[i].cells.length - 1)
	}
}
function deleteColumn(tblId)
{
	var allRows = document.getElementById(tblId).rows;
	for (var i=0; i<allRows.length; i++) {
		if (allRows[i].cells.length > 1) {
			allRows[i].deleteCell(-1);
		}
	}
}
</script>
{% block addcontent %}

<center>
<br>
<h3>Student Attendance List</h3>
<h3>Working Days:{{workingdays}}</h3>
<br>
<div class="container">
<table id="tblSample" class="table table-hover" border="1">
<thead class="tabel table-inverse">
<tr>
  <th>Student ID</th>
<th>Student Name</th>
  <th>Number of Leave days</th>
  
</tr>
</thead>
<tbody>
{% for key,value in classes.items %}
<tr>
  <td>{{key}}</td> 

  <td>{{value.0}}</td>
<td>{{value.1}}</td>
 
</tr>
{% endfor %}
</tbody>
</table>
</div>
</center>
{% endblock %}

SE2017/faculty/templates/course_page.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

<center><h3>Choose Course </h3></center><br>

<center>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
<select  name="dropdown">	
{% for course in Courses %}

<option value="{{course}}" > {{course}}</option>

{% endfor %}
</select><br><br>
        <input type="submit" value="Submit" type="submit" class="btn btn-success">
    </form></center>

SE2017/faculty/templates/forms.html
{% extends "navbar.html" %}
{% block core %}
 <a class="navbar-brand" id="navcourse" href="{% url 'faculty:CoursePage' %}">{{CourseName}}</a>
{% endblock %}
<head>
<style>

.upload{
position:relative;
right:40px;
}
</style>
</head>
{% block addcontent %}
<br>
<div class="jumbotron container">
<center><h4>Upload Assignment </h4></center>
<br>
<center>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}

        {{ form.as_p }}
        <input type="submit" style="margin:5 35 5 5;" onclick="clicked();" value="Upload"class="upload btn btn-success">
        <input type="reset" value="Reset" class="btn btn-warning">
    </form></center>
<p id="demo"></p>
<script>
 function clicked() {

	    var t='<div class="alert alert-success"> <strong>Successfully Uploaded!</strong></div>';
document.getElementById("demo").innerHTML=t;
        
    }
</script>
</div>
{% endblock %}

SE2017/faculty/templates/marks.html
{% extends "navbar.html" %}
{% block core %}
 <a class="navbar-brand" id="navcourse" href="{% url 'faculty:CoursePage' %}">{{CourseName}}</a>
{% endblock %}
{% block head %}
<script>
var vag= document.ElementById('marks');
console.log(vag);

function getContent(){
var s=$('#mytable').html();
console.log(s);
}

function addColumn(tblId)
{
	var tblHeadObj = document.getElementById(tblId).tHead;
	for (var h=0; h<tblHeadObj.rows.length; h++) {
		var newTH = document.createElement('th');
		tblHeadObj.rows[h].appendChild(newTH);
		newTH.innerHTML = '[th] row:' + h + ', cell: ' + (tblHeadObj.rows[h].cells.length - 1)
	}

	var tblBodyObj = document.getElementById(tblId).tBodies[0];
	for (var i=0; i<tblBodyObj.rows.length; i++) {
		var newCell = tblBodyObj.rows[i].insertCell(-1);
		newCell.innerHTML = '[td] row:' + i + ', cell: ' + (tblBodyObj.rows[i].cells.length - 1)
	}
}
function deleteColumn(tblId)
{
	var allRows = document.getElementById(tblId).rows;
	for (var i=0; i<allRows.length; i++) {
		if (allRows[i].cells.length > 1) {
			allRows[i].deleteCell(-1);
		}
	}
}
</script>
{% endblock %}
{% block addcontent %}
<br>
<form action="" method="POST">
{% csrf_token %}

<div id="mytable">
<table id="tblSample"class="table table-hover"name="hello" border="1">
<thead class="thead-inverse">
<tr>
  <th>Student ID</th>
<th>Student Name</th>

{% for assign in assignid %}
  <th>{{assign}}</th>
  {% endfor %}
</tr>
</thead>
<tbody>
{% for student in students %}
<tr>
  <td>{{student.Student_ID.Person_ID}}</td>
<td>{{student.Student_ID.LDAP.username}}</td>
 {% for assign in assignid %}
<td contenteditable="true" name="assign" id="marks"></td>
{% endfor %}
</tr>
{% endfor %}

</tbody>
</table>
</div>
<input type="submit" onclick="getContent();"name="Save1" value="Save">
</form>


{% endblock %}

SE2017/faculty/templates/navbar.html
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
{% block link %}
{% endblock %}

{% block head %}
{% endblock %}
</head>
<style>
.nav > li > a:hover{
	background-color: #000099;
}

</style>

<div class="fluid-container">
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse abc">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
{% block core %}
  <a class="navbar-brand" id="navcourse" href="{% url 'faculty:CoursePage' %}">Navbar</a>
{% endblock %}
  <div class="collapse navbar-collapse main" id="navbarSupportedContent">
    <ul class="nav navbar-nav mr-auto">
	<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle abc active" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
          Assignments
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'faculty:AddAssignment' %}">Upload</a>
          <a class="dropdown-item" href="{% url 'faculty:Delass' %}">View</a>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link active" href="{% url 'faculty:ViewAttendance' %}" >Attendance</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'faculty:index' %}" >Students</a>
      </li>
	<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle abc active" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
          Schedules
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Time Table</a>
          <a class="dropdown-item" href="#">Almanac</a>
        </div>
      </li>
	<li class="nav-item">
        <a class="nav-link active" href="{% url 'faculty:OfferCourses' %}">Offer Courses</a>
      </li>
    </ul>
  </div>
</nav>
{% block addcontent %}
{% endblock %}


</div>

SE2017/faculty/templates/prof.html
{% extends "index.html" %}
{% block content %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

{% if flag == 0 %}

<a href="{% url 'faculty:OfferCourses' %}">Offer Courses</a>
{% else %}

<h2>Please Select a Course</h2><br>
<form action="{% url 'faculty:CoursePage' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
<select  name="dropdown" class="menu" required>
<option value="" selected="selected" hidden> choose course</option>	
{% for course in Courses %}

<option value="{{course}}" > {{course}}</option>

{% endfor %}
</select><br><br>
<input type="submit" name="action" value="submit"  class="btn btn-outline-success">
</form>
{% endif %}

{% endblock %}

SE2017/faculty/templates/prof1.html
{% extends "navbar.html" %}
{% block core %}
 <a class="navbar-brand" id="navcourse" href="{% url 'faculty:CoursePage' %}">{{Course.Course_Name}}</a>
{% endblock %}
{% block addcontent %}
<center><br><br>
<div style="background-color:#ffff99 !important" class="jumbotron container">
<h2>Course Credits:&nbsp{{Course.Course_Credits }}</h2><br>
<h3>Course Description: </h3><br><i>{{Course.Course_description}}</i><br>
<br>

<form id = "citizenForm" action="{% url 'faculty:CoursePage' %}" method="post" style="display:none">
{% csrf_token %}

<textarea style="background-color:#d1e0e0 !important" rows="10" cols="50" name="coursedes">{{Course.Course_description}}</textarea>
<br><br>
 <input type="submit" name="action" class="btn btn-primary btn-md" value="Save">

</form><br>
<button id= "citizenBtn" class="btn btn-primary btn-md" onclick="showForm('citizenForm')">Edit</button>
</div>
<script>

var showForm = function(id){
  document.getElementById(id).style.display = '';
}
 var button = document.getElementById('citizenBtn')
    button.addEventListener('click',hideshow,false);

    function hideshow() {
        
        this.style.display = 'none'
    }   
</script>
</center>
{% endblock %}

SE2017/faculty/templates/reg.html
{% extends "navbar.html" %}
{% block core %}
 <a class="navbar-brand" id="navcourse" href="{% url 'faculty:CoursePage' %}">{{CourseName}}</a>
{% endblock %}
<head>
{% block head %}

<script type="text/javascript">
    var datefield=document.createElement("input")
    datefield.setAttribute("type", "date")
    if (datefield.type!="date"){ //if browser doesn't support input type="date", load files for jQuery UI Date Picker
        document.write('<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />\n')
        document.write('<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"><\/script>\n')
        document.write('<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"><\/script>\n') 
    }
</script>
 
<script>
if (datefield.type!="date"){ //if browser doesn't support input type="date", initialize date picker widget:
    jQuery(function($){ //on document.ready
        $('#duration').datepicker({dateFormat:'yy-mm-dd'}).val();
    })
}
if (datefield.type!="date"){ //if browser doesn't support input type="date", initialize date picker widget:
    jQuery(function($){ //on document.ready
        $('#duration1').datepicker({dateFormat:'yy-mm-dd'}).val();
    })
}
</script>
{% endblock %}
</head>
{% block addcontent %}
<center>
<!--h4><i><b>Offer Courses</b></i></h4-->

<ul>
{% if Courses %}
    {% for course in Courses %}
    
            <form action="{% url 'faculty:OfferCourses' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="checkbox" name="courses[]" value="{{ course.Course_ID }}" />
	<label>{{ course.Course_Name }}</label><br>
    {% endfor %}

<br>
 <label>Start Date</label><input type="date" name="startdate" id="duration"required><br>
 <label>End Date</label><input  type="date" name="enddate" id="duration1"required>

<br>
<input type="submit" onclick="clicked();" value="Submit" />
        </form>
{% else %}
<br><h1 style="color:red;">No Courses To Offer</h1>
{% endif %}
</ul>
<p id="demo"></p>
</center>
<script>
 function clicked() {

	    var t='<div class="alert alert-success"> <strong>Success!</strong></div>';
document.getElementById("demo").innerHTML=t;
        
    }
</script>
{% endblock %}